"""add note listing indexes

Revision ID: 3b22f62d48eb
Revises: e0c62aa7a087
Create Date: 2026-09-17 18:47:37.140491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b22f62d48eb'
down_revision: Union[str, Sequence[str], None] = 'e0c62aa7a087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notes_created_at_id', 'notes', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notes_created_at_id', table_name='notes')
    # ### end Alembic commands ###
